language: objective-c
osx_image: xcode8.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=sample/sample.xcodeproj
  matrix:
    - SCHEME=sample SDK=iphonesimulator
    - SCHEME=sampletv SDK=appletvsimulator
script:
  - set -o pipefail
  - xcodebuild build -project $PROJECT -scheme $SCHEME -sdk $SDK -configuration Release | xcpretty -c
notifications:
  email: false
